In [7]:
import numpy as np
my_arr = np.arange(1000000)     #numpy style
my_list = list (range(1000000)) #python style
%time for i in range(10): my_arr2=my_arr*2   #10번 반복

Wall time: 16 ms


In [8]:
# 일반 파이썬에선 리스트를 그저 두 번 반복할 뿐 그래서
%time for i in range(10): my_list=[x *2 for x in my_list]

Wall time: 945 ms


In [ ]:
#위를 보면 속도 차이가 엄청남

In [10]:
data = np.random.randn(2, 3) # 랜덤수로 채워서 2행3열의 데이터를 만들어라
data

array([[ 0.44130455,  0.55588768,  0.36732688],
       [ 0.80889093, -0.52371395, -0.47283145]])

In [11]:
data * 10

array([[ 4.41304547,  5.55887683,  3.67326881],
       [ 8.08890929, -5.23713946, -4.72831448]])

In [12]:
data + data

array([[ 0.88260909,  1.11177537,  0.73465376],
       [ 1.61778186, -1.04742789, -0.9456629 ]])

In [14]:
data*2 - data

array([[ 0.44130455,  0.55588768,  0.36732688],
       [ 0.80889093, -0.52371395, -0.47283145]])

In [15]:
data.shape # 행렬계산을 하려면 먼저 "전치" 유무를 알기위해 확인할 것

(2, 3)

In [18]:
data = [6, 7.5, 8, 0, 1]
arr = np.array(data)
arr

array([6. , 7.5, 8. , 0. , 1. ])

In [21]:
data2d = [[1,2,3,4], [5,6,7,8]]
data2d

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [24]:
arr2d = np.array(data2d) #어레이로 변환

In [25]:
arr2d.ndim #2차원 확인

2

In [26]:
arr2d.shape #2행 4열 확인

(2, 4)

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros((3, 6)) # Error

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.zeros((2,3,2)).dtype # 정수의 계산이 빠르지만 그것은 CPU 전용 GPU계산은 실수계산

dtype('float64')

In [33]:
arr = np.zeros((2, 3, 2), dtype=np.int32)
arr.dtype

dtype('int32')

In [37]:
arr1 = np.zeros((2, 3,))
arr2 = np.ones_like(arr1) # 이런거랑 비슷한걸 만들어라
arr2.shape
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
arr3 = np.full((2, 3,), 5)
arr3

array([[5, 5, 5],
       [5, 5, 5]])

In [42]:
arr4 = np.eye(2)
arr4

array([[1., 0.],
       [0., 1.]])