In [7]:
import numpy as np
my_arr = np.arange(1000000)     #numpy style
my_list = list (range(1000000)) #python style
%time for i in range(10): my_arr2=my_arr*2   #10번 반복

Wall time: 16 ms


In [8]:
# 일반 파이썬에선 리스트를 그저 두 번 반복할 뿐 그래서
%time for i in range(10): my_list=[x *2 for x in my_list]

Wall time: 945 ms


In [ ]:
#위를 보면 속도 차이가 엄청남

In [10]:
data = np.random.randn(2, 3) # 랜덤수로 채워서 2행3열의 데이터를 만들어라
data

array([[ 0.44130455,  0.55588768,  0.36732688],
       [ 0.80889093, -0.52371395, -0.47283145]])

In [11]:
data * 10

array([[ 4.41304547,  5.55887683,  3.67326881],
       [ 8.08890929, -5.23713946, -4.72831448]])

In [12]:
data + data

array([[ 0.88260909,  1.11177537,  0.73465376],
       [ 1.61778186, -1.04742789, -0.9456629 ]])

In [14]:
data*2 - data

array([[ 0.44130455,  0.55588768,  0.36732688],
       [ 0.80889093, -0.52371395, -0.47283145]])

In [15]:
data.shape # 행렬계산을 하려면 먼저 "전치" 유무를 알기위해 확인할 것

(2, 3)