In [20]:
#p415
from sklearn.datasets import load_files

In [31]:
reviews_train = load_files("C:/Programmierung/workspace/Python_2021/examples/aclImdb/train")

In [32]:
text_train, y_train = reviews_train.data, reviews_train.target

In [33]:
len(text_train)

25000

In [34]:
text_train = [ a_review.replace(b"<br \n>", b" ") for a_review in text_train]

자연어 처리 과정에서 "공백" 등 조심해야함

In [35]:
text_train[0]

b"Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.<br /><br />It is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. In terms of explaining the motives and actions of the two young suicide/murderers it is better than 'Elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see. <br /><br />Flawed but honest with a terrible honesty."

In [36]:
import numpy as np

In [37]:
np.bincount(y_train)

array([12500, 12500], dtype=int64)

In [38]:
reviews_test = load_files("C:/Programmierung/workspace/Python_2021/examples/aclImdb/test")

In [39]:
text_test, y_test = reviews_test.data, reviews_test.target

In [40]:
len(text_test)

25000

In [41]:
np.bincount(y_test)

array([12500, 12500], dtype=int64)

In [45]:
text_test = [a_review.replace(b"<br \n", b" ") for a_review in text_test]

In [50]:
bards_words = ["The fool doth think he is wise,",
              "but the wise man knows himself to be a fool"]

In [51]:
from sklearn.feature_extraction.text import CountVectorizer

In [52]:
vect = CountVectorizer()
vect.fit(bards_words)

CountVectorizer()

In [53]:
len(vect.vocabulary_)

13

In [54]:
vect.vocabulary_

{'the': 9,
 'fool': 3,
 'doth': 2,
 'think': 10,
 'he': 4,
 'is': 6,
 'wise': 12,
 'but': 1,
 'man': 8,
 'knows': 7,
 'himself': 5,
 'to': 11,
 'be': 0}

a 는 제외
12번까지 있는 이유
0~12 번까지

In [56]:
bag_of_words = vect.transform(bards_words)
bag_of_words.toarray()

array([[0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1]], dtype=int64)

각 단어의 중요도? 를 나타냄

순환 신경망 - 순서를 고려해서 신경망을 만듦
보통은 빈출성을 알아냄


bag_of_words(BOW)의 이해를 위한 예제 

In [57]:
vect = CountVectorizer().fit(text_train)

In [59]:
X_train = vect.transform(text_train)

In [61]:
# X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [63]:
feature_names = vect.get_feature_names()
feature_names

['00',
 '000',
 '0000000000001',
 '00001',
 '00015',
 '000s',
 '001',
 '003830',
 '006',
 '007',
 '0079',
 '0080',
 '0083',
 '0093638',
 '00am',
 '00pm',
 '00s',
 '01',
 '01pm',
 '02',
 '020410',
 '029',
 '03',
 '04',
 '041',
 '05',
 '050',
 '06',
 '06th',
 '07',
 '08',
 '087',
 '089',
 '08th',
 '09',
 '0f',
 '0ne',
 '0r',
 '0s',
 '10',
 '100',
 '1000',
 '1000000',
 '10000000000000',
 '1000lb',
 '1000s',
 '1001',
 '100b',
 '100k',
 '100m',
 '100min',
 '100mph',
 '100s',
 '100th',
 '100x',
 '100yards',
 '101',
 '101st',
 '102',
 '102nd',
 '103',
 '104',
 '1040',
 '1040a',
 '1040s',
 '105',
 '1050',
 '105lbs',
 '106',
 '106min',
 '107',
 '108',
 '109',
 '10am',
 '10lines',
 '10mil',
 '10min',
 '10minutes',
 '10p',
 '10pm',
 '10s',
 '10star',
 '10th',
 '10x',
 '10yr',
 '11',
 '110',
 '1100',
 '11001001',
 '1100ad',
 '111',
 '112',
 '1138',
 '114',
 '1146',
 '115',
 '116',
 '117',
 '11f',
 '11m',
 '11th',
 '12',
 '120',
 '1200',
 '1200f',
 '1201',
 '1202',
 '123',
 '12383499143743701',
 '1

In [64]:
len(feature_names)

74849

In [66]:
feature_names[:10]

['00',
 '000',
 '0000000000001',
 '00001',
 '00015',
 '000s',
 '001',
 '003830',
 '006',
 '007']

앞쪽에는 의미없는 단어가 될 확률이 높음

In [69]:
feature_names[20000:20010]

['draper',
 'draperies',
 'drapery',
 'drapes',
 'draskovic',
 'drastic',
 'drastically',
 'drat',
 'dratch',
 'dratic']

중간에는 의미있는 단어들의 러닝

In [70]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [71]:
scores = cross_val_score(LogisticRegression(max_iter=1000), X_train, y_train, cv=5 )

In [72]:
scores

array([0.8812, 0.8768, 0.8814, 0.889 , 0.8794])

In [77]:
X_test = vect.transform(text_test)

In [78]:
lr = LogisticRegression(max_iter=1000).fit(X_train, y_train)
y_pred = lr.predict(X_test[0])

In [79]:
y_pred.shape

(1,)

In [80]:
y_test[0]

1

In [81]:
text_test[0]

b"Don't hate Heather Graham because she's beautiful, hate her because she's fun to watch in this movie. Like the hip clothing and funky surroundings, the actors in this flick work well together. Casey Affleck is hysterical and Heather Graham literally lights up the screen. The minor characters - Goran Visnjic {sigh} and Patricia Velazquez are as TALENTED as they are gorgeous. Congratulations Miramax & Director Lisa Krueger!"

In [82]:
y_test[20000]

1

In [83]:
text_test[15500]

b'Do the writers that conjure up these type of "comedies" have such empty lives that they have to embody them in tragic shows like this?.<br /><br />Why the talented and gorgeous Busy Phillips is amongst this trash is beyond me,I cannot stand the Hispanic girl whose accent sounds very fake and is so unfunny and annoying as is the other African-American girl with the shrill voice.<br /><br />The jokes are often stupid, the Jewish guy yells a lot and the show never goes anywhere, one particular episode with the solider looking for love was just terrible.<br /><br />I don\'t believe there would be that many working in a looking for love office and only one man? Of course all of the Woman are in tight fitting tops and tons of make up to make up for their lack of talent.<br /><br />I actually found Holly funny in her older shows and I have always admired Busy but this show is dumb, empty and had nothing going for it.'